// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/audit": {
            "get": {
                "description": "查询快照操作审计日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "查询审计日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "max items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "action filter",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "snapshot filter",
                        "name": "snapshot",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/device/{connector}/{query_type}": {
            "get": {
                "description": "根据连接器和查询类型查询设备信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "查询设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector name",
                        "name": "connector",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "query type",
                        "name": "query_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "device name",
                        "name": "device",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/monitor/{connector}/{query_type}": {
            "get": {
                "description": "根据连接器和查询类型查询监控数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitor"
                ],
                "summary": "查询监控数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector name",
                        "name": "connector",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "query type",
                        "name": "query_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "device name",
                        "name": "device",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "port name",
                        "name": "port",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "metrics list",
                        "name": "metrics",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start time",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end time",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/snapshot": {
            "get": {
                "description": "返回当前所有快照元数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshot"
                ],
                "summary": "列出所有快照",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的图快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshot"
                ],
                "summary": "创建快照",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/snapshot/diff": {
            "get": {
                "description": "对比两个快照之间的差异",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshot"
                ],
                "summary": "对比快照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "snapshot A name",
                        "name": "a",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "snapshot B name",
                        "name": "b",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/snapshot/restore": {
            "post": {
                "description": "根据名称恢复指定快照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshot"
                ],
                "summary": "恢复快照",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/snapshot/{name}": {
            "delete": {
                "description": "根据名称删除指定快照",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshot"
                ],
                "summary": "删除快照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "snapshot name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sync": {
            "post": {
                "description": "从所有 Connector 全量拉取数据并写入 Neo4j",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "触发全量同步",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SyncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/webhook": {
            "post": {
                "description": "接收 Webhook 增量事件，写入事件队列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "接收增量事件",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/topology": {
            "get": {
                "description": "从 Neo4j 查询图数据库拓扑数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "查询图拓扑",
                "parameters": [
                    {
                        "type": "string",
                        "description": "entity label",
                        "name": "label",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max items",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/topology/live": {
            "get": {
                "description": "直连控制器获取实时拓扑数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "查询实时拓扑",
                "parameters": [
                    {
                        "type": "string",
                        "description": "connector name",
                        "name": "connector",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "返回服务健康状态、时间戳和版本号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.SyncResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "nodes_created": {
                    "type": "integer"
                },
                "orphan_edges_skipped": {
                    "type": "integer"
                },
                "relations_created": {
                    "type": "integer"
                }
            }
        },
        "response.ErrorCode": {
            "type": "integer",
            "enum": [
                0,
                400001,
                401001,
                404001,
                429001,
                500001,
                501001,
                503001,
                400011,
                503011,
                400021,
                404021,
                400031,
                500031,
                400041,
                404041,
                501041,
                400051,
                404051,
                501051
            ],
            "x-enum-comments": {
                "CodeBadRequest": "请求参数错误",
                "CodeCircuitBreakOpen": "服务不可用（熔断）",
                "CodeDeviceBadRequest": "设备请求参数错误",
                "CodeDeviceNotFound": "Connector 未找到",
                "CodeDeviceUnsupported": "设备操作不支持",
                "CodeInternalError": "服务内部错误",
                "CodeMonitorBadRequest": "监控请求参数错误",
                "CodeMonitorNotFound": "监控 Connector 未找到",
                "CodeMonitorUnsupported": "监控操作不支持",
                "CodeNotFound": "资源未找到",
                "CodeNotImplemented": "功能未实现",
                "CodeRateLimitExceed": "请求限流",
                "CodeSnapshotBadRequest": "快照请求参数错误",
                "CodeSnapshotNotFound": "快照未找到",
                "CodeSuccess": "成功",
                "CodeSyncQueueFull": "Webhook 队列满",
                "CodeSyncUnsupportedAction": "不支持的同步动作",
                "CodeTopologyBadRequest": "拓扑请求参数错误",
                "CodeTopologyQueryFailed": "拓扑查询失败",
                "CodeUnauthorized": "未认证"
            },
            "x-enum-descriptions": [
                "成功",
                "请求参数错误",
                "未认证",
                "资源未找到",
                "请求限流",
                "服务内部错误",
                "功能未实现",
                "服务不可用（熔断）",
                "不支持的同步动作",
                "Webhook 队列满",
                "快照请求参数错误",
                "快照未找到",
                "拓扑请求参数错误",
                "拓扑查询失败",
                "设备请求参数错误",
                "Connector 未找到",
                "设备操作不支持",
                "监控请求参数错误",
                "监控 Connector 未找到",
                "监控操作不支持"
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeBadRequest",
                "CodeUnauthorized",
                "CodeNotFound",
                "CodeRateLimitExceed",
                "CodeInternalError",
                "CodeNotImplemented",
                "CodeCircuitBreakOpen",
                "CodeSyncUnsupportedAction",
                "CodeSyncQueueFull",
                "CodeSnapshotBadRequest",
                "CodeSnapshotNotFound",
                "CodeTopologyBadRequest",
                "CodeTopologyQueryFailed",
                "CodeDeviceBadRequest",
                "CodeDeviceNotFound",
                "CodeDeviceUnsupported",
                "CodeMonitorBadRequest",
                "CodeMonitorNotFound",
                "CodeMonitorUnsupported"
            ]
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务错误码，0 = 成功",
                    "allOf": [
                        {
                            "$ref": "#/definitions/response.ErrorCode"
                        }
                    ]
                },
                "data": {},
                "message": {
                    "description": "人类可读描述",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Network Digital Twin API",
	Description:      "网络数字孪生平台 REST API 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
