connectors:
  - name: mock-netbox
    type: mock
    config:
      data_dir: testdata/mock_netbox
    entity_types: [Device, Interface]
  - name: mock-cmdb
    type: mock
    config:
      data_dir: testdata/mock_cmdb
    entity_types: [ISIS, Link, Network_Slice]
