apiVersion: twin.io/v1
kind: EntityType
metadata:
  name: Event
  labels: [Event]
spec:
  identity:
    stableKeys: []
  uriTemplate: ""
  properties:
    timestamp:
      type: string
    severity:
      type: string
    message:
      type: string
